---
- name: Install cleanup_diags.sh
  template:
    src: cleanup_diags.sh.j2
    dest: "{{ splunk_home }}/cleanup_diags.sh"
    owner: root
    group: root
    mode: 0755
  become: true

- name: Configure cron to run cleanup_diags.sh daily at midnight
  cron:
    name: "Run cleanup_diags.sh"
    state: present
    job: "{{ splunk_home }}/cleanup_diags.sh"
    hour: 0
    minute: 0
  become: true
