---
- name: "Run splunk upgrade-{{ peer_state }} cluster-peers on CM"
  command: "{{ splunk_home }}/bin/splunk upgrade-{{ peer_state }} cluster-peers -auth {{ splunk_auth }}"
  become: true
  become_user: "{{ splunk_nix_user }}"
  when:
    - peer_state is defined and splunk_auth is defined
    - "'splunk_clustermaster' in group_names or 'splunk_clustermanager' in group_names"
