---
- name: Splunk offline
  command: "{{ splunk_home }}/bin/splunk offline -auth {{ splunk_auth }}"
  register: splunk_offline_result
  changed_when: splunk_offline_result.rc == 0
  failed_when: splunk_offline_result.rc != 0
  become: true
  become_user: "{{ splunk_nix_user }}"
  no_log: true
